name: build-and-test
run-name: Build and test the changes
on:
  workflow_call:
    inputs:
      build:
        required: false
        type: boolean
        default: false
      build_name:
        required: false
        type: string
        default: Artifact
      pr:
        required: false
        type: string

permissions:
  actions: write
  attestations: write
  contents: read
  pull-requests: read

concurrency:
  group: build-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew check --daemon
  build:
    if: ${{ inputs.build }}
    name: Build
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: LOG-METADATA-1
        run: |
          function output() {
            echo "output:$1=$2"
          }
          output PR_NUMBER "${{ inputs.pr }}"
          output HEAD_SHA "${{ github.sha }}"
      - name: Build with Gradle
        run: ./gradlew build --daemon "-Dmod_artifact_suffix=${{ inputs.pr && format('-pr{0}', inputs.pr) || '' }}-$(git rev-parse --short ${{ github.sha }})"
      - name: Upload Build Artifacts
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('{0} PR {1}', inputs.build_name, inputs.pr) }}
          path: build/libs
          overwrite: true
          if-no-files-found: error
      - name: LOG-METADATA-2
        run: |
          function output() {
            echo "output:$1=$2"
          }
          output ARTIFACT_ID "${{ steps.artifact.outputs.artifact-id }}"
          output ARTIFACT_URL "${{ steps.artifact.outputs.artifact-url }}"
