name: build-and-test
run-name: Build and test the changes and publish and whatever
on:
  workflow_call:
    inputs:
      build_name:
        required: true
        type: string
      pr:
        required: false
        type: string
      check:
        required: false
        type: boolean
        default: true
    outputs:
      artifact-id: ${{ jobs.build.outputs.artifact-id }}
      artifact-name: ${{ jobs.build.outputs.artifact-name }}

permissions:
  actions: write
  attestations: write
  contents: read
  pull-requests: read

concurrency:
  group: build-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: self-hosted
    outputs:
      artifact-id: ${{ steps.artifact.outputs.artifact-id }}
      artifact-name: ${{ inputs.build_name }}
    steps:
      - name: LOG-METADATA-1
        run: |
          function output() {
            echo "output:$1=$2"
          }
          output PR_NUMBER "${{ inputs.pr }}"
          output HEAD_SHA "${{ github.sha }}"
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Gradle Build
        run: ./gradlew build --daemon "-Dmod_artifact_suffix=${{ inputs.pr && format('-pr{0}', inputs.pr) || '' }}-$(git rev-parse --short ${{ github.sha }})"
      - name: Upload Build Artifacts
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.build_name }}
          path: build/libs
          if-no-files-found: error
      - name: LOG-METADATA-2
        run: |
          function output() {
            echo "output:$1=$2"
          }
          output ARTIFACT_ID "${{ steps.artifact.outputs.artifact-id }}"
          output ARTIFACT_URL "${{ steps.artifact.outputs.artifact-url }}"

  check:
    if: ${{ inputs.check }}
    name: Check
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Gradle Check
        run: ./gradlew check --daemon
